# Generated by Django 5.0.4 on 2024-06-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_examen', models.IntegerField(blank=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('groupe', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='photo/')),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exam', models.IntegerField(blank=True)),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('nom', models.CharField(max_length=30)),
                ('semestre', models.IntegerField()),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gdnapp.etudiant')),
                ('examen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gdnapp.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ressource', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('coefficient', models.FloatField()),
                ('UE', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='gdnapp.ue')),
            ],
        ),
    ]
