# Generated by Django 5.0.6 on 2024-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('groupe', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_examen', models.IntegerField()),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=100)),
                ('etudiant', models.CharField(max_length=100)),
                ('note', models.FloatField()),
                ('appreciation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ressource', models.IntegerField()),
                ('nom', models.CharField(max_length=200)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('semestre', models.IntegerField()),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
