# Generated by Django 5.0.4 on 2024-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignants',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
