# Generated by Django 5.0.6 on 2024-05-31 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='enseignant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='gdnapp.enseignants'),
        ),
    ]
