# Generated by Django 5.0.4 on 2024-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdnapp', '0002_alter_enseignants_nom_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
