# Generated by Django 5.0.6 on 2024-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdnapp', '0002_alter_examen_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignants',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
